export type QuestionType = 'single_select' | 'multi_select';
export type Difficulty = 'beginner' | 'intermediate' | 'advanced';

export interface Option {
    id: string;
    text: string;
}

export interface Question {
    id: string;
    type: QuestionType;
    question_text: string;
    options: Option[];
    correct_ids: string[];
    explanation: string;
    why_correct?: string;
    why_incorrect?: string[];
    domain?: string;
    official_link?: string;
    user_selected_ids?: string[];
    is_verified?: boolean;
    marked_for_review?: boolean;
}

export interface Exam {
    id: string;
    name: string;
    provider: string;
    description?: string;
    domains: { name: string; weight: number }[];
    duration_minutes: number;
    total_questions_official: number;
    
    // Admin management fields
    official_guide_url?: string;
    is_active: boolean;
    created_by: string; // admin user id
    created_at: string;
    updated_at: string;

    /** URL de CloudFront de la imagen generada por IA para este examen */
    image_url?: string;

    // Campos dinámicos descubiertos de la guía oficial de la certificación
    target_role?: string;       // Ej: "DevOps Engineer", "Solutions Architect", "Project Manager"
    difficulty_context?: {      // Contexto de dificultad específico de esta certificación
        beginner: string;
        intermediate: string;
        advanced: string;
    };
    system_prompt?: string;     // Prompt de sistema específico para generar preguntas de esta certificación

    usage_stats?: {
        total_attempts: number;
        average_score: number;
        last_attempt: string;
    };
}

export interface ExamDiscoveryResult {
    exam: Exam;
    confidence: 'high' | 'medium' | 'low';
    validation: {
        domains_validated: boolean;
        weights_sum_to_100: boolean;
        official_source_found: boolean;
        isValid: boolean;
        warnings: string[];
    };
    source: 'official_guide' | 'general_knowledge' | 'fallback';
}

export interface ExamAttempt {
    id: string;
    exam_id: string;
    mode: 'simulator' | 'real';
    difficulty: Difficulty;
    
    // Exam length configuration
    exam_length_percentage: 50 | 75 | 100;
    total_questions_requested: number;
    generation_job_id?: string;
    
    // Organization scoping
    org_id?: string;
    
    start_time: string;
    end_time?: string;
    questions: Question[];
    status: 'in_progress' | 'completed' | 'paused';
    score?: number;
    paused_at_index?: number;
}

export interface UserProfile {
    id: string;
    name: string;
    email: string;
    preferred_language: string;
    streak: number;
    last_access: string;
    study_commitment: {
        days: string[]; // ['Mon', 'Wed', 'Fri']
        time: string; // '20:00'
        notifications: boolean;
    };
}

export interface StudyTask {
    id: string;
    text: string;
    completed: boolean;
    official_link?: string;
}

export interface StudyDay {
    day: number;
    title: string;
    tasks: string[]; // IDs of tasks
}

export interface StudyGuide {
    id: string;
    exam_id: string;
    title: string;
    content: string; // Markdown content generated by AI
    weak_areas: string[];
    tasks: StudyTask[];
    plan_days: StudyDay[];
    created_at: string;
}


// Generation Configuration and Progress Tracking
export interface GenerationConfig {
    difficulty: Difficulty;
    language: string;
    totalQuestions: number;
    onProgress?: (progress: GenerationProgress) => void;
    retryAttempts?: number;
    delayBetweenRequests?: number;
}

export interface GenerationProgress {
    current: number;
    total: number;
    currentDomain: string;
    successCount: number;
    failureCount: number;
    estimatedTimeRemaining: number; // seconds
}

export interface GenerationResult {
    questions: Question[];
    stats: GenerationStats;
    errors: GenerationError[];
}

export interface GenerationStats {
    totalGenerated: number;
    totalFailed: number;
    domainDistribution: Map<string, number>;
    totalDuration: number; // milliseconds
    averageTimePerQuestion: number; // milliseconds
}

export interface GenerationError {
    questionIndex: number;
    domain: string;
    error: Error;
    timestamp: Date;
}

export interface DomainQuestionAllocation {
    domain: { name: string; weight: number };
    questionCount: number;
    generated: number;
}

// Block Generation for Progressive Loading
export interface BlockGenerationConfig extends GenerationConfig {
    blockSize: number; // Default: 10
    initialBlockOnly: boolean; // If true, only generate first block
    user_id?: string; // Optional user ID for tracking generation jobs
}

export interface BlockGenerationResult {
    attemptId: string;
    firstBlock: Question[];
    totalRequested: number;
    generationStatus: 'initial_complete' | 'in_progress' | 'completed';
    backgroundJobId?: string;
}

// Background Generation Job Tracking
export interface GenerationJob {
    id: string; // job-{timestamp}
    exam_id: string;
    user_id: string;
    attempt_id: string;
    status: 'pending' | 'in_progress' | 'completed' | 'failed';
    config: GenerationConfig;
    progress?: {
        current: number;
        total: number;
        currentDomain: string;
        eta: number;
    };
    result?: {
        totalGenerated: number;
        totalFailed: number;
    };
    error?: string;
    created_at: string;
    updated_at: string;
}


// Organization Management Types

export interface OrgMember {
    user_id: string;
    email: string;
    full_name: string;
    role: 'org_admin' | 'user';
    description?: string;
    phone?: string;
    joined_at: string;
    access_expires_at?: string;       // ISO date, joined_at + 60 days
}

export interface Organization {
    id: string;
    name: string;
    description: string;
    logo_url?: string;
    email: string;
    phone?: string;
    assigned_exam_ids: string[];
    is_active: boolean;
    created_by: string;
    created_at: string;
    updated_at: string;
    members?: OrgMember[];
}


// Subscription Types for PayPal Integration

export type SubscriptionStatus = 'active' | 'cancelled' | 'expired' | 'grace_period' | 'trial' | 'none';
export type PlanType = 'monthly' | 'annual';

export interface Subscription {
  user_id: string;
  paypal_subscription_id?: string;
  plan_type?: PlanType;
  status: SubscriptionStatus;
  selected_exam_ids: string[];       // max 3
  price_usd?: number;
  start_date?: string;               // ISO date
  current_period_end?: string;        // ISO date
  grace_period_end?: string;          // ISO date
  trial_start_date?: string;          // ISO date
  trial_end_date?: string;            // ISO date
  trial_used: boolean;
  exam_change_used_this_period: boolean;
  cancelled_at?: string;             // ISO date
  admin_free_access?: boolean;       // true if Super Admin granted free access, default false
  created_at: string;                // ISO date
  updated_at: string;                // ISO date
}

export interface ActivateSubscriptionInput {
  paypal_subscription_id: string;
  plan_type: PlanType;
  price_usd: number;
  selected_exam_ids: string[];
}
